name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  simple_deployment_pipeline:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setups-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Run "npm run build" command
      run: npm run build
      
